version: '3.1'
services:
  db:
    image: postgres:9.6-alpine
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d/:ro
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: shortener
      POSTGRES_USER: shortener

networks:
  default:
    driver: bridge

